export const categories = [
      // Left column
      { name: "Blast Freezers", id: "blast-freezers", icon: "❄️" },
      { name: "Blood Bank Refrigerators and Freezers", id: "blood-bank", icon: "🩸" },
      { name: "Centrifuges", id: "centrifuges", icon: "🔄" },
      { name: "Chillers", id: "chillers", icon: "❄️" },
      { name: "Circulating Baths", id: "circulating-baths", icon: "🌊" },
      { name: "CO2 and LN2 Backup Systems", id: "co2-ln2-backup", icon: "🔋" },
      { name: "CO2 Incubators", id: "co2-incubators", icon: "🧪" },
      { name: "Cold Traps", id: "cold-traps", icon: "❄️" },
      { name: "Cryogenics", id: "cryogenics", icon: "🧊" },
      { name: "Cryostats", id: "cryostats", icon: "🧊" },
      { name: "Cycle Chambers", id: "cycle-chambers", icon: "🔄" },
      { name: "Environmental Chambers", id: "environmental-chambers", icon: "🌡️" },
      { name: "Free-Standing Refrigerated Equipment", id: "free-standing-refrigerated", icon: "❄️" },
      { name: "Freeze Driers", id: "freeze-driers", icon: "❄️" },
      { name: "Furnaces", id: "furnaces", icon: "🔥" },
      { name: "Haemobanks", id: "haemobanks", icon: "🩸" },
      { name: "Hot Plates", id: "hot-plates", icon: "🔥" },
      { name: "Humidity Chambers", id: "humidity-chambers", icon: "💧" },
      { name: "Ice Maker Descaling and Sanitization", id: "ice-maker", icon: "🧊" },
      { name: "Incubators", id: "incubators", icon: "🔬" },
      { name: "Laboratory Refrigerators", id: "lab-refrigerators", icon: "❄️" },
      { name: "Liquid Bath Chillers", id: "liquid-bath-chillers", icon: "🧊" },
      { name: "LN2 Freezers", id: "ln2-freezers", icon: "❄️" },
      { name: "Lyophilizers", id: "lyophilizers", icon: "💧" },
      { name: "Microtomes", id: "microtomes", icon: "🔬" },
      { name: "Full Ultra Low-temperature Freezer", id: "ultra-low-freezer", icon: "❄️" },
      { name: "Ovens", id: "ovens", icon: "🔥" },
      { name: "Plasma Refrigerators and Freezers", id: "plasma-refrigerators", icon: "🩸" },
      { name: "Glass Washers", id: "glass-washers", icon: "🧼" },
      { name: "Water Systems", id: "water-systems", icon: "💧" },
      { name: "Autoclaves", id: "autoclaves", icon: "🔬" },
      { name: "Growth Chambers", id: "growth-chambers", icon: "🌱" },
      { name: "Bio Safety Cabinets", id: "bio-safety-cabinets", icon: "🔬" },
      { name: "MRI Chillers", id: "mri-chillers", icon: "🧲" },
      { name: "Thermo Cyclers", id: "thermo-cyclers", icon: "🔄" },
      { name: "Baths", id: "baths", icon: "🌊" },
      { name: "Shakers", id: "shakers", icon: "🔄" },
      { name: "Osmometers", id: "osmometers", icon: "💧" },
      { name: "NIST Temperature Sensors", id: "nist-temperature-sensors", icon: "🌡️" },
  ];
  
  export const brands = [
   // Left column
   { name: "Barnstead", id: "barnstead", icon: "🔬" },
   { name: "Bahnson", id: "bahnson", icon: "❄️" },
   { name: "Baxter", id: "baxter", icon: "🧪" },
   { name: "Beckman Coulter", id: "beckman-coulter", icon: "🧬" },
   { name: "Binder", id: "binder", icon: "🔬" },
   { name: "Continental", id: "continental", icon: "🧊" },
   { name: "Conviron", id: "conviron", icon: "🌱" },
   { name: "Follet", id: "follet", icon: "❄️" },
   { name: "Forma", id: "forma", icon: "🧪" },
   { name: "Hacker", id: "hacker", icon: "🔬" },
   { name: "Haskris", id: "haskris", icon: "❄️" },
   { name: "Hettich", id: "hettich", icon: "🔄" },
   { name: "Harris", id: "harris", icon: "🧪" },
   { name: "Jeuan", id: "jeuan", icon: "🔬" },
   { name: "Kendro", id: "kendro", icon: "🧪" },
   { name: "Lauda", id: "lauda", icon: "🌡️" },
   { name: "Labconco", id: "labconco", icon: "🧪" },
   { name: "Labline", id: "labline", icon: "🔬" },
   { name: "Lancer", id: "lancer", icon: "🧼" },
   { name: "Lunaier", id: "lunaier", icon: "❄️" },
   { name: "Lynx", id: "lynx", icon: "🔬" },
   { name: "Memmert", id: "memmert", icon: "🌡️" },
   { name: "Nuaire", id: "nuaire", icon: "🧬" },
   { name: "Panasonic", id: "panasonic", icon: "🔋" },
   { name: "Percival", id: "percival", icon: "🌱" },
   { name: "Powers Scientific", id: "powers-scientific", icon: "🔬" },
   { name: "Precision Scientific", id: "precision-scientific", icon: "⚗️" },
   { name: "Revco", id: "revco", icon: "❄️" },
   { name: "Sanyo", id: "sanyo", icon: "🧊" },
   { name: "Savant", id: "savant", icon: "🔬" },
   { name: "Stirling", id: "stirling", icon: "❄️" },
   { name: "Taylor Wharton", id: "taylor-wharton", icon: "🧊" },
   { name: "Tenney", id: "tenney", icon: "🌡️" },
   { name: "Thermal Product Solutions", id: "thermal-product-solutions", icon: "🔥" },
   { name: "Thermo Electron", id: "thermo-electron", icon: "🔬" },
   { name: "Thermo Fisher Scientific", id: "thermo-fisher-scientific", icon: "🧪" },
   { name: "True", id: "true", icon: "❄️" },
   { name: "VWR", id: "vwr", icon: "🧪" },
   { name: " Z-SC1", id: "z-sci", icon: "🔬" },
  ];
 