export const postsData = [
    {
        id: 1,
        title: "ALL Scientific's New Repair Depot Opens",
        description: "AllScientific's New Repair Depot Opens",
        author: "Steven Gottfried",
        date: "May 12, 2024",
        readTime: "0 min read",
        views: 37,
        comments: 0,
        likes: 1,
        image: "/assets/images/posts/post-one.webp",
        isLiked: false
      },
      {
        id: 2,
        title: "ALL Scientific's New Repair Depot Opens",
        description: "AllScientific's New Repair Depot Opens",
        author: "Steven Gottfried",
        date: "May 12, 2024",
        readTime: "1 min read",
        views: 47,
        comments: 4,
        likes: 1,
        image: "/assets/images/posts/post-three.webp",
        isLiked: false
      },
      {
        id: 4,
        title: "ALL Scientific's New Trucks are on the Road",
        description: "Expanding our fleet to better serve our customers",
        author: "Steven Gottfried",
        date: "May 12, 2024",
        readTime: "2 min read",
        views: 52,
        comments: 6,
        likes: 1,
        image: "/assets/images/posts/post-two.webp",
        isLiked: false
      },
      {
        id: 5,
        title: "The Lifeline of Blood Banks: Precision Refrigeration for Safe Storage",
        description: "Blood Bank Every drop of blood stored represents a lifeline for patients in critical need. Whether for trauma care, life-saving ",
        author: "Steven Gottfried",
        date: "May 12, 2024",
        readTime: "2 min read",
        views: 1,
        comments: 0,
        likes: 1,
        image: "/assets/images/posts/post-five.webp",
        isLiked: false
      },
      {
        id: 6,
        title: "MRI Downtime: Strategies for Reliable Medical Imaging Operations",
        description: "MRI facilities rely on precise temperature control to ensure accurate imaging, patient safety, and operational efficiency.",
        author: "Steven Gottfried",
        date: "May 12, 2024",
        readTime: "2 min read",
        views: 52,
        comments: 6,
        likes: 1,
        image: "/assets/images/posts/post-six.webp",
        isLiked: false
      },
      {
        id: 7,
        title: "Advancements in MRI Technology: Transforming Patient Care",
        description: "Historical Perspective: The Evolution of MRI Technology Since its clinical adoption in the early 1980s, magnetic resonance imaging (MRI)",
        author: "Steven Gottfried",
        date: "May 12, 2024",
        readTime: "2 min read",
        views: 52,
        comments: 6,
        likes: 1,
        image: "/assets/images/posts/post-seven.webp",
        isLiked: false
      },
      {
        id: 8,
        title: "The Key to Lab Success: Preventive Maintenance for Ultra Low Temperature",
        description: "Ultra low temperature freezers are critical to scientific research, preserving irreplaceable biological samples, reagents",
        author: "Steven Gottfried",
        date: "May 12, 2024",
        readTime: "2 min read",
        views: 52,
        comments: 6,
        likes: 1,
        image: "/assets/images/posts/post-eight.webp",
        isLiked: false
      },
      {
        id: 3,
        title: "ALL Scientific's New Office Opens",
        description: "ALL Scientific's New Office Opens",
        author: "Steven Gottfried",
        date: "May 12, 2024",
        readTime: "1 min read",
        views: 52,
        comments: 5,
        likes: 1,
        image: "/assets/images/posts/post-four.webp",
        isLiked: false
      },
      {
        id: 9,
        title: "Ultra Low Temperature Freezer Calibration and Its Importance",
        description: "The Science Behind Calibration Calibration is the process of verifying an instrument's measurements against a known, traceable standard. ", 
        author: "Steven Gottfried",
        date: "May 12, 2024",
        readTime: "2 min read",
        views: 52,
        comments: 6,
        likes: 1,
        image: "/assets/images/posts/post-nine.webp",
        isLiked: false
      },
      // Add remaining posts here...
    ];
    